Iter15
kTowkA/shortener pull request #15
Opened 2024-05-18 21:08 UTC by kTowkA

2024-05-21 14:56 UTC, Perederey requested changes
Надо переделать, но а целом хорошо 

Проверь batch на постгрессе
Раздели воркер и handler и запускай воркер в го рутине

2024-05-21 14:56 UTC, Perederey commented on internal/app/app.go
> +	defaultSecretKey = "my_super_secret_key"
Это можно в конфиг

2024-05-21 14:56 UTC, Perederey commented on internal/app/app.go
> +	secretKey string
А зачем тебе переменная тут?

2024-05-21 14:56 UTC, Perederey commented on internal/app/app.go
> +	ticker := time.NewTicker(10 * time.Second)
У тебя должна быть отдельно логика handler и отдельно воркер. Сейчас у тебя хендлер вызывает Воркер, если пользователь закроет приложение, то твой воркер закроется. Если два пользоваться зайдут, то у тебя будет два тикера. Попробуй открыть сразу 100 страниц в разное время и увидишь результат

2024-05-21 14:56 UTC, Perederey commented on internal/app/app.go
> +	for {
И круто было бы увидеть тест

2024-05-21 14:56 UTC, Perederey commented on internal/app/route.go
> +	if w.Header().Get("content-type") == "" {
Только лучше Content-Type

2024-05-21 14:56 UTC, Perederey commented on internal/app/route.go
> +	if err != nil {
Закрыть забыл Body

2024-05-21 14:56 UTC, Perederey commented on internal/storage/memory/memory.go
> +	// но при загрузке обновленные значения перепишут значения в памяти, так что для упрощения оставляем так
Хорошо :)

2024-05-21 14:56 UTC, Perederey commented on internal/storage/postgres/psql.go
> +		tc, err := br.Exec()
А зачем делать это много раз, если ты уже сделал batch? Разве не достаточно вызвать один раз?

2024-05-21 20:31 UTC, kTowkA commented on internal/app/app.go
> +	ticker := time.NewTicker(10 * time.Second)
flushDeleteMessages никак не связан с хендлерами. Он и вызывается в горутине (как Вы и просили выше) в методе ListenAndServe(), которая отвечает за запуск сервера. Несколько пользователей не запустят несколько тикеров. ListenAndServe срабатывает только в исполняемом файле один раз, хендлеры вообще ни при чем. Он запускается один раз при старте и все. В учебнике в примере с алисой типа такого и было, только там воркер запускался при создании экземпляра

2024-05-21 20:32 UTC, kTowkA commented on internal/app/app.go
> +	for {
Там у вас в курсе проверяется и TestDelete/check_state, и TestDeleteConcurrent. И все работает отлично

2024-05-21 20:37 UTC, kTowkA commented on internal/storage/postgres/psql.go
> +		tc, err := br.Exec()
Из комментария к методу: Exec reads the results from the next query in the batch as if the query has been sent with Conn.Exec
Батч выполняется при закрытии, а такая конструкция служит если есть желание собрать ошибки по конкретным запросам, я решил собрать для полноты картины

2024-05-24 16:19 UTC, Perederey commented on internal/app/app.go
> +	ticker := time.NewTicker(10 * time.Second)
Хорошо

2024-05-24 16:20 UTC, Perederey commented on internal/app/app.go
> +	for {
Это конечно круто, но важно руку самому набить

2024-05-24 16:21 UTC, Perederey commented on internal/storage/postgres/psql.go
> +		tc, err := br.Exec()
Хорошо, но немного намудрил

2024-05-24 16:21 UTC, Perederey approved these changes
Теперь все отлично

2024-05-26 13:49 UTC, merged